'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {AppShell} from '@/components/shell/AppShell';
import {api} from '@/services/emps-api';
import {amenities,AssetRow,Draft,draftFrom,emptyDraft,Station,reviewLabels} from './station-types';
import {StationPhoto} from './StationPhoto';
import {StationTeam} from './StationTeam';
import {StationSummary} from './StationSummary';
import styles from './platform.module.css';
const steps=['Localização','Informações','Energia','Carregadores','Fotos e Comodidades','Revisão'];
const days=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];
export function StationWizard({id}:{id?:string}){
 const [station,setStation]=useState<Station|null>(null),[draft,setDraft]=useState<Draft>(emptyDraft),[stationId,setStationId]=useState(id),[step,setStep]=useState(0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(!!id),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const creating=useRef<Promise<Station>|null>(null),saving=useRef(false);
 useEffect(()=>{if(!id)return;let alive=true;void api.platform<Station>('/v2/stations/'+id).then(s=>{if(alive){setStation(s);setDraft(draftFrom(s))}}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[id]);
 const owner=!station||station.membershipRole==='OWNER',canEdit=!station||['OWNER','MANAGER'].includes(station.membershipRole),pending=station?.reviewState==='PENDING_REVIEW'||station?.technicalReviewRequired,disabled=busy||!canEdit||!!pending;
 function set(key:string,value:unknown){setDraft(d=>({...d,[key]:value}))}
 async function ensureId(){if(stationId)return stationId;if(!creating.current)creating.current=api.platform<Station>('/v2/stations',{method:'POST'});try{const s=await creating.current;setStationId(s.id);setStation(s);return s.id}catch(e){creating.current=null;throw e}}
 async function save(submit=false){if(saving.current)return;saving.current=true;setBusy(true);setError('');setNotice('');try{const sid=await ensureId();const baseline=station?draftFrom(station):null;const payload=station?.status==='ACTIVE'&&baseline?Object.fromEntries(Object.entries(draft).filter(([k,v])=>JSON.stringify(v)!==JSON.stringify(baseline[k]))):draft;let s=await api.platform<Station>('/v2/stations/'+sid,{method:'PATCH',body:JSON.stringify(payload)});if(submit){await api.platform('/v2/stations/'+sid+'/submit',{method:'POST'});s=await api.platform<Station>('/v2/stations/'+sid)}setStation(s);setDraft(draftFrom(s));setNotice(submit?'Estação enviada para análise.':s.technicalReviewRequired?'Alterações técnicas enviadas para revisão. A configuração aprovada continua em operação.':'Rascunho salvo. Você pode continuar depois.');history.replaceState(null,'','/stations/'+sid)}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar')}finally{setBusy(false);saving.current=false}}
 function field(key:string,label:string,type='text',source:Record<string,unknown>=draft,onChange:(k:string,v:unknown)=>void=set){return <label key={key}>{label}<input type={type} step={type==='number'?'any':undefined} value={String(source[key]??'')} onChange={e=>onChange(key,type==='number'?(e.target.value===''?undefined:Number(e.target.value)):e.target.value)}/></label>}
 function assetFields(key:'batteries'|'solarAssets'|'chargers',index:number,fields:[string,string,string?][]){const row=draft[key][index];return <div className={styles.fields}>{fields.map(([k,label,type])=>field(k,label,type,row,(name,value)=>set(key,draft[key].map((r,i)=>i===index?{...r,[name]:value}:r))))}</div>}
 function assetStatus(key:'batteries'|'solarAssets',index:number){return <label>Status do ativo<select value={draft[key][index].status??'CONFIGURED'} onChange={e=>set(key,draft[key].map((a,i)=>i===index?{...a,status:e.target.value}:a))}>{[['CONFIGURED','Configurado'],['ACTIVE','Ativo'],['INACTIVE','Inativo'],['FAULTED','Com falha']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
 function add(key:'batteries'|'solarAssets'|'chargers',row:AssetRow){set(key,[...draft[key],row])}
 async function upload(file:File,position:number){setBusy(true);setError('');try{const sid=await ensureId();const body=new FormData();body.append('position',String(position));body.append('file',file);await api.platform('/v2/stations/'+sid+'/photos',{method:'POST',body});setStation(await api.platform<Station>('/v2/stations/'+sid));setNotice('Foto salva.')}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar a foto')}finally{setBusy(false)}}
 return <AppShell eyebrow="EMPS / Estações" title={station?.name??'Nova estação'} description="Configure no seu ritmo e envie para validação quando estiver pronto."><div className={styles.page}>
  <div className={styles.toolbar}><Link href="/stations">← Minhas estações</Link><span className={styles.tag}>{reviewLabels[station?.reviewState??'DRAFT']}</span></div>
  {loading?<p role="status">Carregando rascunho…</p>:<>
  <nav className={styles.steps} aria-label="Etapas do cadastro">{steps.map((name,i)=><button key={name} className={i===step?styles.active:''} aria-current={i===step?'step':undefined} onClick={()=>setStep(i)}><span>{i+1}</span>{name}</button>)}</nav>
  <progress max={6} value={step+1} aria-label="Progresso do cadastro"/>
  {error&&<p className={styles.error} role="alert">{error}</p>}{notice&&<p className={styles.notice} role="status">{notice}</p>}{pending&&<p className={styles.notice}>Há uma análise pendente. {station?.status==='ACTIVE'?'A configuração aprovada permanece ativa.':'A estação ficará privada até a aprovação.'}</p>}
  {station?.reviews?.[0]?.reason&&<p className={styles.notice}>Última revisão: {station.reviews[0].reason}</p>}
  <fieldset disabled={disabled} className={styles.panel}><h2>{step+1}. {steps[step]}</h2>
   {step===0&&<div className={styles.fields}>{[['countryCode','País (código)','text'],['postalCode','CEP (8 dígitos)','text'],['state','Estado (UF)','text'],['city','Cidade','text'],['neighborhood','Bairro','text'],['street','Rua','text'],['addressNumber','Número','text'],['complement','Complemento','text'],['latitude','Latitude','number'],['longitude','Longitude','number'],['timezone','Fuso horário','text']].map(([k,l,t])=>field(k,l,t))}</div>}
   {step===1&&<><div className={styles.fields}>{field('name','Nome da estação')}<label>Tipo de local<select value={String(draft.venueType)} onChange={e=>set('venueType',e.target.value)}>{[['posto','Posto'],['shopping','Shopping'],['condominio','Condomínio'],['empresa','Empresa'],['residencial','Residência / pequeno negócio'],['hotel','Hotel'],['estacionamento','Estacionamento'],['concessionaria','Concessionária'],['outro','Outro']].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Descrição curta<textarea value={String(draft.description??'')} maxLength={500} onChange={e=>set('description',e.target.value)}/></label><label>Visibilidade<select value={draft.visibility} onChange={e=>set('visibility',e.target.value)}><option value="PRIVATE">Privada · acesso autorizado</option><option value="PUBLIC">Pública · visível no App após aprovação</option></select></label>{field('openingHours','Horário informado ao cliente')}</div><label className={styles.check}><input type="checkbox" checked={draft.availability.alwaysOpen} onChange={e=>set('availability',{...draft.availability,alwaysOpen:e.target.checked})}/>Disponível para recarga 24 horas</label>{!draft.availability.alwaysOpen&&<>{draft.availability.windows.map((w,i)=><div className={styles.row} key={i}><label>Dia<select value={w.day} onChange={e=>set('availability',{...draft.availability,windows:draft.availability.windows.map((a,j)=>j===i?{...a,day:Number(e.target.value)}:a)})}>{days.map((d,j)=><option value={j} key={d}>{d}</option>)}</select></label>{(['start','end'] as const).map(k=><label key={k}>{k==='start'?'Início':'Fim'}<input type="time" value={w[k]} onChange={e=>set('availability',{...draft.availability,windows:draft.availability.windows.map((a,j)=>j===i?{...a,[k]:e.target.value}:a)})}/></label>)}<button onClick={()=>set('availability',{...draft.availability,windows:draft.availability.windows.filter((_,j)=>j!==i)})}>Remover janela</button></div>)}<button onClick={()=>set('availability',{...draft.availability,windows:[...draft.availability.windows,{day:1,start:'19:00',end:'07:00'}]})}>+ Horário disponível</button><small className={styles.small}>O horário pode atravessar a meia-noite. Início e fim iguais representam 24 horas naquele dia.</small></>}<label className={styles.check}><input type="checkbox" checked={!!draft.guestAllowed} onChange={e=>set('guestAllowed',e.target.checked)}/>Permitir Web Charge como visitante quando a estação for pública</label></>}
   {step===2&&<>{field('powerLimitKw','Limite de potência da rede (kW)','number')}<label className={styles.check}><input type="checkbox" checked={draft.solarAssets.length>0} onChange={e=>set('solarAssets',e.target.checked?[{name:'Solar 1',installedKwp:5,status:'CONFIGURED'}]:[])}/>Possui energia solar?</label>{draft.solarAssets.map((a,i)=><section className={styles.equipment} key={String(a.id??i)}><h3>Conjunto solar {i+1}</h3>{assetFields('solarAssets',i,[['name','Nome'],['installedKwp','Potência instalada (kWp)','number'],['acPowerKw','Potência AC (kW)','number'],['inverter','Inversor'],['manufacturer','Fabricante'],['model','Modelo'],['integrationRef','Referência de integração (opcional)']])}{assetStatus('solarAssets',i)}<button onClick={()=>set('solarAssets',draft.solarAssets.filter((_,j)=>j!==i))}>Retirar conjunto</button></section>)}{draft.solarAssets.length>0&&<button onClick={()=>add('solarAssets',{name:'Solar '+(draft.solarAssets.length+1),installedKwp:5,status:'CONFIGURED'})}>+ Conjunto solar</button>}<label className={styles.check}><input type="checkbox" checked={draft.batteries.length>0} onChange={e=>set('batteries',e.target.checked?[{name:'Bateria 1',capacityKwh:10,maxChargeKw:5,maxDischargeKw:5,minSocPercent:10,maxSocPercent:95,efficiency:.95,status:'CONFIGURED'}]:[])}/>Possui armazenamento / bateria?</label>{draft.batteries.map((a,i)=><section className={styles.equipment} key={String(a.id??i)}><h3>Bateria {i+1}</h3>{assetFields('batteries',i,[['name','Nome'],['capacityKwh','Capacidade (kWh)','number'],['maxChargeKw','Carga máxima (kW)','number'],['maxDischargeKw','Descarga máxima (kW)','number'],['socPercent','SOC informado (%) · opcional','number'],['minSocPercent','SOC mínimo (%)','number'],['maxSocPercent','SOC máximo (%)','number'],['efficiency','Eficiência (0 a 1)','number'],['manufacturer','Fabricante'],['model','Modelo'],['integrationRef','Referência de integração (opcional)']])}{assetStatus('batteries',i)}<button onClick={()=>set('batteries',draft.batteries.filter((_,j)=>j!==i))}>Retirar bateria</button></section>)}{draft.batteries.length>0&&<button onClick={()=>add('batteries',{name:'Bateria '+(draft.batteries.length+1),capacityKwh:10,maxChargeKw:5,maxDischargeKw:5,minSocPercent:10,maxSocPercent:95,efficiency:.95,status:'CONFIGURED'})}>+ Bateria</button>}<p className={styles.small}>Solar e baterias são opcionais. Os valores informados são configuração; não representam telemetria medida.</p></>}
   {step===3&&<>{draft.chargers.map((a,i)=><section className={styles.equipment} key={String(a.id??i)}><h3>Carregador {i+1}</h3>{assetFields('chargers',i,[['name','Nome'],['manufacturer','Fabricante'],['model','Modelo'],['serialNumber','Serial'],['powerKw','Potência máxima (kW)','number'],['connectorType','Conector'],['ocppIdentity','Identidade OCPP'],['firmwareVersion','Firmware'],['pricePerKwh','Tarifa base (R$/kWh)','number']])}<label>Status administrativo<select value={a.administrativeStatus??'PENDING'} onChange={e=>set('chargers',draft.chargers.map((c,j)=>j===i?{...c,administrativeStatus:e.target.value}:c))}><option value="PENDING">Pendente de ativação</option><option value="ENABLED">Habilitado</option><option value="MAINTENANCE">Manutenção</option><option value="DISABLED">Desabilitado</option></select></label><button onClick={()=>set('chargers',draft.chargers.filter((_,j)=>j!==i))}>Retirar carregador</button></section>)}<button onClick={()=>add('chargers',{name:'Carregador '+(draft.chargers.length+1),ocppIdentity:'EMPS-'+crypto.randomUUID(),powerKw:7.4,connectorType:'TYPE2',administrativeStatus:'PENDING'})}>+ Adicionar carregador</button><p className={styles.small}>Você pode salvar um rascunho sem carregadores. A ativação exige validação.</p></>}
   {step===4&&<><h3>1 foto principal + até 4 adicionais</h3><div className={styles.photos}>{[0,1,2,3,4].map(position=><div key={position}><StationPhoto version={station?.photos.find(p=>p.position===position)?.storageKey} id={station?.photos.find(p=>p.position===position)?.id} alt={position===0?'Foto principal':'Foto adicional '+position}/><label>{position===0?'Principal':'Adicional '+position}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f,position)}}/></label></div>)}</div><small className={styles.small}>JPEG, PNG ou WebP · máximo de 8 MB por foto.</small><h3>Comodidades</h3><div className={styles.amenities}>{amenities.map(a=><label className={styles.check} key={a}><input type="checkbox" checked={draft.amenities.includes(a)} onChange={e=>set('amenities',e.target.checked?[...draft.amenities,a]:draft.amenities.filter(v=>v!==a))}/>{a}</label>)}</div></>}
   {step===5&&<><StationSummary draft={draft}/><p className={styles.small}>{station?.status==='ACTIVE'?'Alterações técnicas importantes são enviadas para nova revisão.':'Após o envio, uma pessoa autorizada da plataforma revisará a configuração.'}</p></>}
  </fieldset>
  <div className={styles.toolbar}><button disabled={disabled} onClick={()=>void save()}>Salvar rascunho / alterações</button><div className={styles.actions}><button disabled={step===0} onClick={()=>setStep(s=>s-1)}>Voltar</button>{step<5?<button className={styles.primary} onClick={()=>setStep(s=>s+1)}>Continuar</button>:owner&&station?.status!=='ACTIVE'&&<button className={styles.primary} disabled={disabled} onClick={()=>void save(true)}>Enviar para análise</button>}</div></div>
  {stationId&&canEdit&&<StationTeam stationId={stationId} owner={owner}/>}
  {stationId&&station&&<Link className={styles.button} href={'/stations/'+stationId+'/telemetry'}>Dados, histórico e readiness do GIE</Link>}
  {stationId&&station&&['OWNER','MANAGER','OPERATOR','COLLECTOR'].includes(station.membershipRole)&&<Link className={styles.button} href={'/stations/'+stationId+'/rfid'}>RFID e rateio mensal</Link>}
  </>}
 </div></AppShell>;
}
