'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {api} from '@/services/emps-api';
import {AppShell} from '@/components/shell/AppShell';
import styles from './platform.module.css';
type Credential={id:string;label:string;unitReference:string|null;userId:number|null;vehicleReference:string|null;organization:string|null;enabled:boolean;expiresAt:string|null};
type Report={month:string;timezone:string;groups:{unitReference:string|null;resident:string;sessions:number;kwh:string;referenceAmount:string}[];sessions:{sessionId:string;kwh:string;referenceAmount:string;provenance:string}[]};
type Station={name:string;chargers:{id:string;name:string}[];membershipRole:string};
const money=(value:string)=>Number(value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export function StationRfid({id}:{id:string}){
 const path='/v2/stations/'+id+'/rfid';
 const [station,setStation]=useState<Station|null>(null),[rows,setRows]=useState<Credential[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [uid,setUid]=useState(''),[label,setLabel]=useState(''),[unit,setUnit]=useState(''),[user,setUser]=useState(''),[vehicle,setVehicle]=useState(''),[organization,setOrganization]=useState(''),[expires,setExpires]=useState('');
 const [scan,setScan]=useState(''),[charger,setCharger]=useState(''),[revoke,setRevoke]=useState<Credential|null>(null),[month,setMonth]=useState(()=>new Date().toISOString().slice(0,7)),[report,setReport]=useState<Report|null>(null);
 useEffect(()=>{let alive=true;void api.platform<Station>('/v2/stations/'+id).then(s=>{if(alive){setStation(s);setCharger(String(s.chargers[0]?.id??''))}if(['OWNER','MANAGER'].includes(s.membershipRole))return api.platform<Credential[]>('/v2/stations/'+id+'/rfid').then(r=>{if(alive)setRows(r)})}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[id]);
 async function act(work:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await work()}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir')}finally{setBusy(false)}}
 const manage=station&&['OWNER','MANAGER'].includes(station.membershipRole),operate=station&&['OWNER','MANAGER','OPERATOR','COLLECTOR'].includes(station.membershipRole);
 return <AppShell eyebrow="EMPS / RFID" title={station?.name??'RFID e rateio'} description="Credenciais por estação e consumo para fechamento mensal."><div className={styles.page}>
  <Link href={'/stations/'+id}>← Voltar à estação</Link>
  <p className={styles.notice}>RFID identifica e autoriza acesso. Não efetua pagamento automático. A demonstração usa energia simulada; integração física GoodWe pendente.</p>
  {error&&<p className={styles.error} role="alert">{error}</p>}{notice&&<p className={styles.notice} role="status">{notice}</p>}
  {manage&&<><section className={styles.panel}><h2>Credenciais</h2><div className={styles.tableWrap}><table><thead><tr><th>Identificação</th><th>Unidade / usuário</th><th>Veículo / organização</th><th>Validade</th><th>Ação</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td>{c.label}<br/>{c.enabled?'Ativa':'Revogada'}</td><td>{c.unitReference??'—'} / {c.userId??'—'}</td><td>{c.vehicleReference??'—'} / {c.organization??'—'}</td><td>{c.expiresAt?new Date(c.expiresAt).toLocaleString('pt-BR'):'Sem vencimento'}</td><td>{c.enabled&&<button disabled={busy} onClick={()=>setRevoke(c)}>Revogar {c.label}</button>}</td></tr>)}</tbody></table></div>{rows.length===0&&<p>Nenhuma credencial cadastrada.</p>}
  {revoke&&<div className={styles.notice}><p>Revogar {revoke.label}? Novos inícios serão bloqueados; sessões e histórico serão preservados.</p><button disabled={busy} onClick={()=>setRevoke(null)}>Cancelar</button> <button disabled={busy} onClick={()=>void act(async()=>{await api.platform(path+'/'+revoke.id+'/revoke',{method:'POST'});setRows(await api.platform<Credential[]>(path));setRevoke(null);setNotice('Credencial revogada.')})}>Confirmar revogação</button></div>}
  <form onSubmit={e=>{e.preventDefault();void act(async()=>{await api.platform(path,{method:'POST',body:JSON.stringify({uid,label,unitReference:unit||undefined,userId:user?Number(user):undefined,vehicleReference:vehicle||undefined,organization:organization||undefined,expiresAt:expires?new Date(expires).toISOString():undefined})});setRows(await api.platform<Credential[]>(path));setUid('');setLabel('');setNotice('Credencial cadastrada somente nesta estação.')})}}><div className={styles.fields}>
  <label>UID do cartão<input required maxLength={80} value={uid} onChange={e=>setUid(e.target.value)} placeholder="Ex.: AABBCCDD" autoComplete="off"/></label><label>Nome / identificação<input required maxLength={100} value={label} onChange={e=>setLabel(e.target.value)}/></label>
  <label>Unidade<input maxLength={100} value={unit} onChange={e=>setUnit(e.target.value)}/></label><label>ID do usuário (opcional)<input type="number" min="1" step="1" value={user} onChange={e=>setUser(e.target.value)}/></label>
  <label>Veículo<input maxLength={100} value={vehicle} onChange={e=>setVehicle(e.target.value)}/></label><label>Empresa / frota<input maxLength={100} value={organization} onChange={e=>setOrganization(e.target.value)}/></label><label>Válida até (horário deste dispositivo)<input type="datetime-local" value={expires} onChange={e=>setExpires(e.target.value)}/></label></div><p className={styles.small}>O UID não fica disponível para consulta após o cadastro.</p><button className={styles.primary} disabled={busy}>Cadastrar credencial</button></form></section>
  <section className={styles.panel}><h2>Fechamento mensal</h2><form className={styles.row} onSubmit={e=>{e.preventDefault();void act(async()=>setReport(await api.platform<Report>(path+'/monthly?month='+encodeURIComponent(month))))}}><label>Mês<input type="month" required value={month} onChange={e=>{setMonth(e.target.value);setReport(null)}}/></label><button disabled={busy}>Consultar consumo</button></form>{report&&<><p>Referência para rateio · mês do encerramento · fuso {report.timezone}. Nenhum pagamento coletado por este relatório.</p><div className={styles.tableWrap}><table><thead><tr><th>Unidade</th><th>Morador / credencial</th><th>Sessões</th><th>kWh</th><th>Valor de referência</th></tr></thead><tbody>{report.groups.map((g,i)=><tr key={i}><td>{g.unitReference??'—'}</td><td>{g.resident}</td><td>{g.sessions}</td><td>{Number(g.kwh).toFixed(3)}</td><td>{money(g.referenceAmount)}</td></tr>)}</tbody></table></div>{report.sessions.length===0&&<p>Nenhuma sessão concluída neste mês.</p>}<p className={styles.small}>{report.sessions.map(s=>'Sessão '+s.sessionId+' · '+s.provenance).join(' / ')}</p></>}</section></>}
  {operate&&<section className={styles.panel}><h2>Identificação e teste Demo</h2><div className={styles.fields}><label>UID para leitura de teste<input value={scan} onChange={e=>setScan(e.target.value)} autoComplete="off"/></label><label>Carregador<select value={charger} onChange={e=>setCharger(e.target.value)}>{station.chargers.map(c=><option value={String(c.id)} key={c.id}>{c.name}</option>)}</select></label></div><div className={styles.actions}>
  <button disabled={busy||!scan} onClick={()=>void act(async()=>{const r=await api.platform<{label:string}>(path+'/authorize',{method:'POST',body:JSON.stringify({uid:scan})});setNotice('Credencial autorizada: '+r.label+'. Nenhuma cobrança efetuada.')})}>Verificar autorização</button>
  <button disabled={busy||!scan||!charger} onClick={()=>void act(async()=>{const r=await api.platform<{sessionId:string}>(path+'/demo/'+charger+'/start',{method:'POST',body:JSON.stringify({uid:scan})});setNotice('Sessão Demo '+r.sessionId+' iniciada. Consumo simulado para rateio; sem pagamento individual.')})}>Iniciar Demo</button>
  <button disabled={busy||!charger} onClick={()=>void act(async()=>{await api.platform(path+'/demo/'+charger+'/stop',{method:'POST'});setNotice('Sessão RFID Demo encerrada. Consulte o consumo mensal.')})}>Encerrar Demo</button></div></section>}
 </div></AppShell>;
}
