'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {api} from '@/services/emps-api';
import {AppShell} from '@/components/shell/AppShell';
import styles from './platform.module.css';
const origins=['MEASURED','CALCULATED','EXTERNAL','FORECAST','SIMULATED','IMPORTED'];
const names:Record<string,string>={MEASURED:'Medição física',CALCULATED:'Calculado',EXTERNAL:'Fonte externa',FORECAST:'Previsão',SIMULATED:'Simulação',IMPORTED:'Histórico importado',UNCLASSIFIED_LEGACY:'Legado sem classificação'};
type Readiness={station_id:string;latestTrustedTelemetryAt:string|null;model:string;realDataDays:number|null;qualityPercent:number|null;coveragePercent:number|null;usableConsumptionIntervals:number;personalizationAvailable:boolean;analysisTruncated:boolean;provenanceCounts:{origin:string;count:number}[];blockers:string[];gieContract:unknown};
type Source={id:string;label:string;kind:string;enabled:boolean;verifiedPhysical:boolean};
type Reading={id:string;measuredAt:string;provenance:string|null;buildingPowerKw:string|null;chargerPowerKw:string|null;outsideTemperatureC:string|null;relativeHumidityPercent:string|null;sourceId:string|null};
type Preview={rows:number;first:string;last:string;provenance:string;sha256:string;modelActivated:boolean};
export function StationTelemetry({id}:{id:string}){
 const path='/v2/stations/'+id+'/telemetry';
 const [station,setStation]=useState<{name:string;timezone:string;membershipRole:string}|null>(null),[ready,setReady]=useState<Readiness|null>(null),[sources,setSources]=useState<Source[]>([]),[history,setHistory]=useState<Reading[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [from,setFrom]=useState(()=>new Date(Date.now()-30*86400000).toISOString().slice(0,10)),[to,setTo]=useState(()=>new Date(Date.now()+86400000).toISOString().slice(0,10)),[origin,setOrigin]=useState(''),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<Preview|null>(null),[sourceName,setSourceName]=useState(''),[sourceKind,setSourceKind]=useState('SIMULATED'),[token,setToken]=useState(''),[datasetOrigin,setDatasetOrigin]=useState('MEASURED'),[model,setModel]=useState('building');
 const manage=station&&['OWNER','MANAGER'].includes(station.membershipRole);
 useEffect(()=>{let alive=true;void Promise.all([api.platform<{name:string;timezone:string;membershipRole:string}>('/v2/stations/'+id),api.platform<Readiness>('/v2/stations/'+id+'/telemetry/readiness')]).then(async([s,r])=>{if(!alive)return;setStation(s);setReady(r);if(['OWNER','MANAGER'].includes(s.membershipRole)){const rows=await api.platform<Source[]>('/v2/stations/'+id+'/telemetry/sources');if(alive)setSources(rows)}}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[id]);
 async function act(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir')}finally{setBusy(false)}}
 const range=()=>new URLSearchParams({from:new Date(from+'T00:00:00Z').toISOString(),to:new Date(to+'T00:00:00Z').toISOString()});
 async function upload(commit:boolean){if(!file||!station)return;const body=new FormData();body.append('file',file);body.append('timezone',station.timezone);body.append('mode',commit?'commit':'preview');const result=await api.platform<Preview>(path+'/import',{method:'POST',body});if(commit){setNotice('Histórico importado com origem IMPORTED. Nenhum modelo foi ativado.');setPreview(null);setReady(await api.platform<Readiness>(path+'/readiness'));setSources(await api.platform<Source[]>(path+'/sources'))}else setPreview(result)}
 function download(name:string,value:string,mime:string){const url=URL.createObjectURL(new Blob([value],{type:mime})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <AppShell eyebrow="EMPS / Dados e GIE" title={station?.name??'Dados e GIE'} description="Origem dos dados, histórico e preparação para personalização."><div className={styles.page}><Link href={'/stations/'+id}>← Voltar à estação</Link>{busy&&<p role="status" aria-live="polite">Processando solicitação… Aguarde a confirmação.</p>}{error&&<p role="alert" className={styles.error}>{error}</p>}{notice&&<p role="status" className={styles.notice}>{notice}</p>}
 {ready&&<><section className={styles.panel}><h2>{ready.model}</h2><div className={styles.summary}><section><h3>Dados físicos</h3><p>{ready.realDataDays??'Análise limitada'} dias observados</p></section><section><h3>Qualidade registrada</h3><p>{ready.qualityPercent===null?'Sem dados físicos':ready.qualityPercent+'%'}</p></section><section><h3>Consumo em intervalos de 15 min</h3><p>{ready.usableConsumptionIntervals} intervalos completos</p><p>Cobertura: {ready.coveragePercent===null?'Sem histórico elegível':ready.coveragePercent+'%'}</p></section><section><h3>Última telemetria confiável</h3><p>{ready.latestTrustedTelemetryAt?new Date(ready.latestTrustedTelemetryAt).toLocaleString('pt-BR',{timeZone:station?.timezone}):'Nenhuma leitura física confiável'}</p></section><section><h3>Personalização</h3><p>Ainda não disponível</p><p>Não há treinamento ou ativação automáticos.</p></section></div><ul>{ready.blockers.map(b=><li key={b}>{b}</li>)}</ul><p className={styles.small}>Qualidade: proporção de leituras físicas verificadas com qualidade GOOD. Cobertura: intervalos completos entre a primeira e a última observação elegível. Dados importados, previsões e Demo não contam como medição física. Retenção planejada de 24 meses, sem exclusão automática.</p></section><section className={styles.panel}><h2>Origem dos registros</h2>{ready.provenanceCounts.length?ready.provenanceCounts.map(p=><p key={p.origin}>{names[p.origin]??p.origin}: {p.count}</p>):<p>A estação ainda não possui telemetria registrada.</p>}</section></>}
 <section className={styles.panel}><h2>Histórico</h2><div className={styles.fields}><label>De (UTC)<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Até, exclusivo (UTC)<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Origem<select value={origin} onChange={e=>setOrigin(e.target.value)}><option value="">Todas</option>{origins.map(o=><option key={o} value={o}>{names[o]}</option>)}</select></label></div><button disabled={busy} onClick={()=>void act(async()=>{const q=range();if(origin)q.set('provenance',origin);setHistory(await api.platform<Reading[]>(path+'/history?'+q))})}>Consultar histórico</button><div className={styles.tableWrap}><table><thead><tr><th>Instante</th><th>Origem</th><th>Prédio (kW)</th><th>Recarga (kW)</th><th>Temperatura (°C)</th><th>Umidade (%)</th></tr></thead><tbody>{history.map(r=><tr key={r.id}><td>{new Date(r.measuredAt).toLocaleString('pt-BR',{timeZone:station?.timezone})}</td><td>{names[r.provenance??'UNCLASSIFIED_LEGACY']}</td><td>{r.buildingPowerKw??'—'}</td><td>{r.chargerPowerKw??'—'}</td><td>{r.outsideTemperatureC??'—'}</td><td>{r.relativeHumidityPercent??'—'}</td></tr>)}</tbody></table></div><p className={styles.small}>Até 1000 registros recentes no período. Horários da tabela no fuso {station?.timezone}.</p></section>
 {manage&&<><section className={styles.panel}><h2>Importar histórico</h2><p>CSV ou XLSX, até 8 MB e 10000 linhas. Intervalos contínuos de 15 minutos; timestamps ISO com offset, em ordem. Unidades: kW, °C e %. A origem será sempre IMPORTED.</p><button onClick={()=>download('modelo-historico.csv','timestamp,building_power_kw,outside_temperature_c,relative_humidity_percent\n','text/csv')}>Baixar modelo CSV</button><label>Arquivo histórico<input type="file" accept=".csv,.xlsx" onChange={e=>{setFile(e.target.files?.[0]??null);setPreview(null)}}/></label><button disabled={busy||!file} onClick={()=>void act(()=>upload(false))}>Validar arquivo</button>{preview&&<div className={styles.notice}><p>{preview.rows} linhas · {preview.first} até {preview.last} · IMPORTED</p><p>Não substitui medições existentes nem ativa modelos.</p><button disabled={busy} onClick={()=>void act(()=>upload(true))}>Confirmar importação</button></div>}</section>
 <section className={styles.panel}><h2>Dataset para validação futura</h2><p>Usa o período do histórico acima. Não mistura previsões ou simulações com medições. Importações exigem escolha explícita e validação posterior.</p><div className={styles.fields}><label>Origem do dataset<select value={datasetOrigin} onChange={e=>setDatasetOrigin(e.target.value)}><option value="MEASURED">Somente medições físicas verificadas</option><option value="IMPORTED">Somente histórico importado</option></select></label><label>Modelo<select value={model} onChange={e=>setModel(e.target.value)}><option value="building">Consumo do prédio</option><option value="chargers">Demanda dos carregadores</option></select></label></div><button disabled={busy} onClick={()=>void act(async()=>{const q=range();q.set('origin',datasetOrigin);q.set('model',model);const result=await api.platform<{rows:unknown[];gaps:number}>(path+'/dataset?'+q);download('emps-estacao-'+id+'-'+model+'-'+datasetOrigin+'.json',JSON.stringify(result,null,2),'application/json');setNotice('Dataset exportado: '+result.rows.length+' intervalos, '+result.gaps+' lacunas. Nenhum treinamento iniciado.')})}>Exportar dataset</button></section>
 <details className={styles.panel}><summary>Fontes e integração</summary><p>O token permite envio somente para esta estação e para a origem cadastrada. MEASURED exige verificação física por revisor autorizado. Não habilite hardware sem evidência.</p>{sources.map(source=><p key={source.id}>{source.label} · {names[source.kind]} · {source.enabled?'Habilitada':'Revogada / importação concluída'}{source.kind==='MEASURED'&&(source.verifiedPhysical?' · física verificada':' · aguardando verificação')}</p>)}<form onSubmit={e=>{e.preventDefault();void act(async()=>{const source=await api.platform<Source&{token:string}>(path+'/sources',{method:'POST',body:JSON.stringify({label:sourceName,kind:sourceKind})});setToken(source.token);setSources(await api.platform<Source[]>(path+'/sources'));setNotice('Fonte criada. Guarde o token somente na integração autorizada.')})}}><div className={styles.fields}><label>Nome da fonte<input required maxLength={100} value={sourceName} onChange={e=>setSourceName(e.target.value)}/></label><label>Origem fixa<select value={sourceKind} onChange={e=>setSourceKind(e.target.value)}>{origins.filter(o=>o!=='IMPORTED').map(o=><option key={o} value={o}>{names[o]}</option>)}</select></label></div><button disabled={busy}>Criar fonte</button></form>{token&&<p className={styles.invite}>Token exibido uma vez: <code>{token}</code></p>}</details>
 <section className={styles.panel}><h2>Contrato GIE V2</h2><p>Configuração por estação com ativos individuais. A ativação do serviço multiestação é uma etapa futura; o GIE atual permanece preservado.</p><button disabled={!ready?.gieContract} onClick={()=>download('gie-v2-estacao-'+id+'.json',JSON.stringify(ready?.gieContract,null,2),'application/json')}>Exportar configuração aprovada</button></section></>}
 </div></AppShell>;
}
