'use client';
import {authReturnPath} from '@/services/auth-return';
import {FormEvent,useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {api} from '@/services/emps-api';
export default function RegisterPage(){
 const router=useRouter();const [nextPath,setNextPath]=useState('/stations');useEffect(()=>setNextPath(authReturnPath()),[]);const [name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[terms,setTerms]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const submitting=useRef(false);
 async function submit(e:FormEvent){e.preventDefault();if(submitting.current)return;if(password!==confirmation){setError('As senhas precisam ser iguais.');return}submitting.current=true;setBusy(true);setError('');try{await api.register({name,email,password,passwordConfirmation:confirmation,acceptTerms:terms});router.replace(authReturnPath())}catch(e){setError(e instanceof Error?e.message:'Não foi possível criar a conta')}finally{setBusy(false);submitting.current=false}}
 return <main className="login-screen" data-theme="dark"><section className="login-visual" aria-label="Energia e mobilidade EMPS"/><section className="login-panel"><form className="login-card" onSubmit={submit}><Image src="/emps-logo-red.png" alt="EMPS" width={180} height={60} className="login-logo"/><h1>Sua conta EMPS</h1><p>Uma conta para o Site, o App e suas recargas.</p><div className="login-fields"><label htmlFor="name">Nome</label><input id="name" autoComplete="name" required minLength={2} maxLength={100} value={name} onChange={e=>setName(e.target.value)}/><label htmlFor="email">E-mail</label><input id="email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/><label htmlFor="password">Senha</label><input id="password" type="password" autoComplete="new-password" minLength={8} maxLength={72} required value={password} onChange={e=>setPassword(e.target.value)}/><label htmlFor="confirmation">Confirme a senha</label><input id="confirmation" type="password" autoComplete="new-password" minLength={8} maxLength={72} required value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></div><label className="login-check"><input type="checkbox" required checked={terms} onChange={e=>setTerms(e.target.checked)}/><span>Li e aceito os Termos de Uso e a Política de Privacidade do EMPS.</span></label>{error&&<p className="login-error" role="alert">{error}</p>}<button className="login-submit" disabled={busy}>{busy?'Criando conta…':'Criar conta'}</button><footer className="login-footer">Já tem conta? <Link href={"/login?next="+encodeURIComponent(nextPath)}>Entrar</Link></footer></form></section></main>;
}
