import {useEffect,useState} from 'react';
import {useLocalSearchParams,useRouter} from 'expo-router';
import {ScrollView,StyleSheet,Text,TextInput,View,Pressable} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {useApp} from '@/context/app-context';
import {AppButton} from '@/components/ui/app-button';
import {Colors,Fonts,MaxContentWidth} from '@/constants/theme';
type Quote={fee:string;termsHash:string;paymentMode:string;policy:{text?:string;timezone:string;noShowMinutes:number;cancellation:string};energyIncluded:false};
type Booking={id:string;chargerId:string;startAt:string;endAt:string;status:string;fee:string;provider:string|null;providerPaymentId:string|null;policySnapshot:{text?:string;refundStatus?:string;payment?:{amount:string;paidAt:string}};station?:{name:string};charger?:{name:string}};
const names:Record<string,string>={PENDING_PAYMENT:'Aguardando pagamento',CONFIRMED:'Confirmada',CANCELLED:'Cancelada',EXPIRED:'Expirada',USED:'Utilizada',NO_SHOW:'Não compareceu'};
const money=(v:string)=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function Reservations(){
 const {stationId}=useLocalSearchParams<{stationId:string}>(),router=useRouter();
 const {reservationRequest,loadStation,getStation,getStationChargers,isDemoMode}=useApp();
 const station=getStation(stationId),chargers=getStationChargers(stationId);
 const [charger,setCharger]=useState(''),[date,setDate]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[quote,setQuote]=useState<Quote|null>(null),[accepted,setAccepted]=useState(false),[rows,setRows]=useState<Booking[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[cancel,setCancel]=useState<string|null>(null),[requestKey,setRequestKey]=useState('');
 useEffect(()=>{if(isDemoMode)return;let alive=true;void Promise.all([loadStation(stationId),reservationRequest<Booking[]>('')]).then(([s,r])=>{if(alive){setCharger(s.chargerIds[0]??'');setRows(r)}}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[stationId,isDemoMode,loadStation,reservationRequest]);
 const reset=()=>{setQuote(null);setAccepted(false);setRequestKey('')};
 function input(){if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(start)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(end))throw Error('Informe data AAAA-MM-DD e horários HH:MM.');return {chargerId:String(charger),startAt:new Date(date+'T'+start+':00').toISOString(),endAt:new Date(date+'T'+end+':00').toISOString()}}
 async function act(work:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await work()}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir')}finally{setBusy(false)}}
 const refresh=async()=>setRows(await reservationRequest<Booking[]>(''));
 return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.content}><AppButton title="Voltar" variant="ghost" onPress={()=>router.back()}/><Text style={s.title}>Agendar carregador</Text><Text style={s.text}>{station?.name??'Carregando estação…'}</Text>
 {!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}{!!notice&&<Text style={s.text}>{notice}</Text>}
 {isDemoMode?<Text style={s.text}>Agendamento exige conexão com a API. Desative o modo de dados locais para continuar.</Text>:<>
 <View style={s.card}><Text style={s.text}>Carregador</Text>{chargers.map(c=><AppButton key={c.id} title={(String(c.id)===String(charger)?'✓ ':'')+c.label} variant="secondary" onPress={()=>{setCharger(c.id);reset()}}/>)}
 <Text style={s.text}>Data (AAAA-MM-DD)</Text><TextInput accessibilityLabel="Data da reserva" value={date} onChangeText={v=>{setDate(v);reset()}} placeholder="2026-10-02" placeholderTextColor={Colors.textMuted} style={s.input}/>
 <Text style={s.text}>Início (HH:MM)</Text><TextInput accessibilityLabel="Horário inicial" value={start} onChangeText={v=>{setStart(v);reset()}} placeholder="14:00" placeholderTextColor={Colors.textMuted} style={s.input}/>
 <Text style={s.text}>Fim (HH:MM)</Text><TextInput accessibilityLabel="Horário final" value={end} onChangeText={v=>{setEnd(v);reset()}} placeholder="15:00" placeholderTextColor={Colors.textMuted} style={s.input}/>
 <Text style={s.small}>Informe os horários no fuso deste dispositivo: {Intl.DateTimeFormat().resolvedOptions().timeZone}. Reservas de até 24 horas, no mesmo dia.</Text>
 <AppButton title="Consultar disponibilidade e taxa" disabled={busy||!charger} onPress={()=>void act(async()=>{const q=await reservationRequest<Quote>('/quote',input());setQuote(q);setAccepted(false);setRequestKey('reservation-'+Date.now()+'-'+Math.random().toString(36).slice(2))})}/>
 {quote&&<><Text style={s.title}>Taxa de reserva: {money(quote.fee)}</Text><Text style={s.text}>Energia e eventual permanência são cobradas separadamente.</Text><Text style={s.text}>{quote.policy.text}</Text><Text style={s.small}>Fuso da estação: {quote.policy.timezone}. Tolerância de chegada: {quote.policy.noShowMinutes} minutos. Cancelamento de reserva paga: devolução sujeita à análise manual.</Text><Text style={s.text}>{quote.paymentMode==='FREE'?'Sem taxa de reserva.':quote.paymentMode==='SANDBOX'?'Pagamento Demo/Sandbox. Nenhuma transação bancária real.':'Pagamento ainda indisponível.'}</Text>
 <Pressable accessibilityRole="checkbox" accessibilityState={{checked:accepted}} onPress={()=>setAccepted(!accepted)}><Text style={s.text}>{accepted?'☑':'☐'} Li e aceito a política e a taxa de reserva.</Text></Pressable>
 <AppButton title="Criar reserva" disabled={busy||!accepted||quote.paymentMode==='UNAVAILABLE'} onPress={()=>void act(async()=>{const r=await reservationRequest<Booking>('',{...input(),termsHash:quote.termsHash,acceptPolicy:accepted,idempotencyKey:requestKey});setNotice(r.status==='CONFIRMED'?'Reserva confirmada.':'Horário aguardando pagamento Demo por até 10 minutos.');setQuote(null);await refresh()})}/></>}
 </View><Text style={s.title}>Minhas reservas</Text><AppButton title="Atualizar reservas" variant="secondary" disabled={busy} onPress={()=>void act(refresh)}/>
 {rows.map(r=><View key={r.id} style={s.card}><Text style={s.title}>{r.station?.name} · {r.charger?.name}</Text><Text style={s.text}>{names[r.status]??r.status}</Text><Text style={s.text}>{new Date(r.startAt).toLocaleString('pt-BR')} — {new Date(r.endAt).toLocaleString('pt-BR')}</Text><Text style={s.text}>Taxa de reserva: {money(r.fee)} · Energia não incluída</Text><Text style={s.small}>{r.policySnapshot.text??'Política registrada na confirmação.'}</Text>{r.provider==='SANDBOX'&&<><Text style={s.text}>Comprovante Demo/Sandbox · taxa paga: {money(r.policySnapshot.payment?.amount??r.fee)}</Text><Text style={s.small}>Referência {r.providerPaymentId}. Não é documento fiscal nem pagamento bancário real.</Text></>}{r.policySnapshot.refundStatus==='PENDING_MANUAL_REVIEW'&&<Text style={s.text}>Devolução pendente de análise manual.</Text>}
 {r.status==='PENDING_PAYMENT'&&<AppButton title="Pagar taxa no Demo/Sandbox" disabled={busy} onPress={()=>void act(async()=>{await reservationRequest('/'+r.id+'/pay-demo',{});await refresh()})}/>}
 {['CONFIRMED','PENDING_PAYMENT'].includes(r.status)&&<AppButton title="Cancelar reserva" variant="secondary" disabled={busy} onPress={()=>setCancel(r.id)}/>}{cancel===r.id&&<><Text style={s.text}>Confirmar cancelamento? A vaga será liberada.</Text><AppButton title="Voltar sem cancelar" variant="ghost" onPress={()=>setCancel(null)}/><AppButton title="Confirmar cancelamento" disabled={busy} onPress={()=>void act(async()=>{await reservationRequest('/'+r.id+'/cancel',{});setCancel(null);await refresh()})}/></>}
 </View>)}{rows.length===0&&<Text style={s.text}>Nenhuma reserva encontrada.</Text>}</>}
 </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:Colors.background},content:{padding:20,gap:18,width:'100%',maxWidth:MaxContentWidth,alignSelf:'center'},card:{padding:18,gap:14,backgroundColor:Colors.surface,borderRadius:18},title:{fontFamily:Fonts.bold,color:Colors.text,fontSize:20},text:{fontFamily:Fonts.regular,color:Colors.text,lineHeight:23},small:{fontFamily:Fonts.regular,color:Colors.textMuted,fontSize:12,lineHeight:19},error:{color:Colors.coral},input:{borderWidth:1,borderColor:Colors.borderSoft,borderRadius:10,padding:13,color:Colors.text,fontFamily:Fonts.regular}});
