import 'reflect-metadata';
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { PrismaClient } from '@prisma/client';
import { PlatformAccessService } from '../src/platform-access.service';
import { PlatformStationsService } from '../src/platform-stations.service';
import { StationMembersService } from '../src/station-members.service';
import { OperationsController } from '../src/operations.controller';
import { MobileService } from '../src/mobile.service';
import { eligibleStationWhere } from '../src/station-visibility';
import { StationPhotosService, imageType } from '../src/station-photos';

test('MySQL V2: isolamento, convites, lifecycle e ativos; fixtures integralmente revertidas',{skip:process.env.EMPS_V2_MYSQL_TEST!=='true'},async()=>{
 process.loadEnvFile('.env');const db=new PrismaClient(),rollback=Error('ROLLBACK_TEST_FIXTURES');
 try{await assert.rejects(db.$transaction(async tx=>{
  const adapter=new Proxy(tx,{get:(t,key)=>key==='$transaction'?async(fn:any)=>fn(adapter):(t as any)[key]}) as any;
  const notices:any[]=[];const notifications={send:async(kind:any,payload:any)=>{notices.push({kind,payload});return {delivery:'LOCAL_OUTBOX'}}} as any;
  const access=new PlatformAccessService(adapter),stations=new PlatformStationsService(adapter,access,notifications),members=new StationMembersService(adapter,access,notifications);
  const owner=await tx.user.create({data:{name:'V2 test owner',email:randomUUID()+'@example.invalid',passwordHash:'not-a-login-hash',role:'CUSTOMER'}});
  const outsider=await tx.user.create({data:{name:'V2 test outsider',email:randomUUID()+'@example.invalid',passwordHash:'not-a-login-hash',role:'ADMIN'}});
  const manager=await tx.user.create({data:{name:'V2 test manager',email:randomUUID()+'@example.invalid',passwordHash:'not-a-login-hash',role:'CUSTOMER'}});
  const reviewer=await tx.user.create({data:{name:'V2 test reviewer',email:randomUUID()+'@example.invalid',passwordHash:'not-a-login-hash',role:'CUSTOMER',platformReviewer:true}});
  const auth=(u:any)=>({sub:String(u.id),role:u.role,email:u.email});
  const files=new Map<string,Buffer>();
  const photos=new StationPhotosService(adapter,access,{put:async(buffer:Buffer)=>{const key=randomUUID();files.set(key,buffer);return key},read:async(key:string)=>{if(!files.has(key))throw Error('missing');return files.get(key)!},remove:async(key:string)=>{files.delete(key)}} as any);
  assert.equal((await stations.list(auth(owner))).length,0);
  const a=await stations.create(auth(owner)),b=await stations.create(auth(outsider));
  assert.equal(a.reviewState,'DRAFT');assert.equal(a.chargers.length,0);assert.equal((await tx.user.findUniqueOrThrow({where:{id:owner.id}})).role,'CUSTOMER');
  const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2n9sAAAAASUVORK5CYII=','base64');
  const upload={buffer:png,size:png.length,mimetype:'image/png'};
  assert.throws(()=>imageType(Buffer.from('<svg onload="alert(1)"></svg>')),/JPEG/);
  await assert.rejects(photos.save(auth(outsider),String(a.id),0,upload),/Sem permissão/);
  const firstPhoto=await photos.save(auth(owner),String(a.id),0,upload);
  const replacement=await photos.save(auth(owner),String(a.id),0,upload);
  assert.equal(replacement.id,firstPhoto.id);assert.notEqual(replacement.storageKey,firstPhoto.storageKey);assert.equal(files.size,1);
  await assert.rejects(photos.read(replacement.id),/não encontrada/);
  await assert.rejects(photos.read(replacement.id,auth(outsider)),/Sem permissão/);
  assert.deepEqual((await photos.read(replacement.id,auth(owner))).data,png);
  await assert.rejects(stations.get(auth(owner),String(b.id)),/Sem permissão/);
  await assert.rejects(stations.save(auth(owner),String(b.id),{name:'Forbidden'}),/Sem permissão/);
  await members.invite(auth(owner),String(a.id),{email:manager.email,role:'MANAGER'});
  await stations.save(auth(manager),String(a.id),{name:'Autorizada'});
  await assert.rejects(members.invite(auth(manager),String(a.id),{email:outsider.email,role:'OPERATOR'}),/Sem permissão/);
  await members.change(auth(owner),String(a.id),String(manager.id),{role:'VIEWER'});
  await assert.rejects(stations.save(auth(manager),String(a.id),{name:'Forbidden'}),/Sem permissão/);
  await members.change(auth(owner),String(a.id),String(manager.id),null);
  await assert.rejects(stations.get(auth(manager),String(a.id)),/Sem permissão/);
  const inviteEmail=randomUUID()+'@example.invalid';const invitation=await members.invite(auth(owner),String(a.id),{email:inviteEmail,role:'OPERATOR'});
  await assert.rejects(members.accept(auth(outsider),invitation.invitationToken!),/Convite inválido/);
  const invited=await tx.user.create({data:{name:'V2 invited',email:inviteEmail,passwordHash:'not-a-login-hash',role:'CUSTOMER'}});
  await members.accept(auth(invited),invitation.invitationToken!);await assert.rejects(members.accept(auth(invited),invitation.invitationToken!),/Convite inválido/);
  assert.equal((await access.require(auth(invited),a.id,'OPERATE')).membershipRole,'OPERATOR');
  await assert.rejects(access.require(auth(invited),a.id,'MANAGE'),/Sem permissão/);
  const charger=await tx.charger.create({data:{stationId:a.id,name:'V2 test charger',publicCode:'TEST-'+randomUUID(),ocppIdentity:randomUUID(),connectorType:'TYPE2',powerKw:7,administrativeStatus:'PENDING'}});
  const ops=new OperationsController(adapter,{} as any,{publish:()=>{}} as any);
  await assert.rejects(ops.charger({user:auth(outsider),headers:{}} as any,String(charger.id)),/não encontrado/);
  assert.equal((await ops.chargers({user:auth(owner),headers:{}} as any)).length,1);
  const mobile=new MobileService(adapter,{} as any,{} as any,{} as any,{} as any);
  await assert.rejects(mobile.station(String(a.id),String(outsider.id)),/não encontrado/);
  await stations.save(auth(owner),String(a.id),{name:'Teste V2',street:'Rua Teste',city:'São Paulo',state:'SP',postalCode:'01001000',latitude:-23.55,longitude:-46.63,powerLimitKw:30,visibility:'PRIVATE',batteries:[{name:'B1',capacityKwh:10,maxChargeKw:5,maxDischargeKw:5,socPercent:10,minSocPercent:10,maxSocPercent:95,efficiency:.95,status:'CONFIGURED'},{name:'B2',capacityKwh:90,maxChargeKw:20,maxDischargeKw:20,socPercent:90,minSocPercent:10,maxSocPercent:95,efficiency:.95,status:'CONFIGURED'}]});
  assert.equal((await stations.get(auth(owner),String(a.id))).storage.socPercent,82);
  const review=await stations.submit(auth(owner),String(a.id));
  await assert.rejects(stations.review(auth(owner),review.id,{decision:'APPROVED',reason:'teste'}),/restrita/);
  await stations.review(auth(reviewer),review.id,{decision:'CHANGES_REQUESTED',reason:'Ajustar para teste'});
  await stations.save(auth(owner),String(a.id),{solarAssets:[{name:'Solar teste',installedKwp:5,status:'CONFIGURED'}]});
  const second=await stations.submit(auth(owner),String(a.id));
  await assert.rejects(stations.review(auth(reviewer),second.id,{decision:'APPROVED',reason:'Demo teste',activateDemoChargers:true}),/restrita/);
  await tx.user.update({where:{id:reviewer.id},data:{presentationTools:true}});
  await tx.tariff.create({data:{stationId:a.id,chargerId:charger.id,name:'Teste',basePricePerKwh:2,status:'ACTIVE',validFrom:new Date()}});
  await stations.review(auth(reviewer),second.id,{decision:'APPROVED',reason:'Aprovada para teste',activateDemoChargers:true});
  assert.equal((await tx.chargerLiveStatus.findUniqueOrThrow({where:{chargerId:charger.id}})).operationalStatus,'AVAILABLE');
  assert.equal(await tx.qrBinding.count({where:{chargerId:charger.id,isActive:true}}),1);
  assert.equal(await tx.chargingCommand.count({where:{chargerId:charger.id,type:'RUN_CHECKLIST'}}),1);
  assert.equal(Object.hasOwn(second.proposedConfig as object,'reviews'),false);
  assert.equal(await tx.station.count({where:{id:a.id,...eligibleStationWhere()}}),0);
  assert.equal(await tx.station.count({where:{id:a.id,...eligibleStationWhere(owner.id)}}),1);
  await stations.save(auth(owner),String(a.id),{visibility:'PUBLIC'});assert.equal(await tx.station.count({where:{id:a.id,...eligibleStationWhere()}}),1);
  assert.deepEqual((await photos.read(replacement.id)).data,png);
  assert.deepEqual((await photos.read(replacement.id,auth(outsider))).data,png);
  await stations.save(auth(owner),String(a.id),{batteries:[],solarAssets:[]});assert.equal((await stations.get(auth(owner),String(a.id))).storage.count,2);
  const pending=await tx.stationReview.findFirstOrThrow({where:{stationId:a.id,state:'PENDING_REVIEW'}});await stations.review(auth(reviewer),pending.id,{decision:'APPROVED',reason:'Retirada autorizada'});
  assert.equal((await stations.get(auth(owner),String(a.id))).storage.count,0);assert.equal(await tx.stationBattery.count({where:{stationId:a.id}}),2);
  const retiredSolar=await tx.stationSolarAsset.findMany({where:{stationId:a.id}});assert.equal(retiredSolar.length,1);assert.equal(retiredSolar[0].status,'INACTIVE');
  throw rollback;
 },{timeout:60000}),e=>e===rollback)}finally{await db.$disconnect()}
});
